In [1]:
import numpy as np
import pandas as pd


train = pd.read_csv('../kaggle_data/train.csv')

In [2]:
train

row_id  cfips          county    state first_day_of_month  \
0        1001_2019-08-01   1001  Autauga County  Alabama         2019-08-01   
1        1001_2019-09-01   1001  Autauga County  Alabama         2019-09-01   
2        1001_2019-10-01   1001  Autauga County  Alabama         2019-10-01   
3        1001_2019-11-01   1001  Autauga County  Alabama         2019-11-01   
4        1001_2019-12-01   1001  Autauga County  Alabama         2019-12-01   
...                  ...    ...             ...      ...                ...   
122260  56045_2022-06-01  56045   Weston County  Wyoming         2022-06-01   
122261  56045_2022-07-01  56045   Weston County  Wyoming         2022-07-01   
122262  56045_2022-08-01  56045   Weston County  Wyoming         2022-08-01   
122263  56045_2022-09-01  56045   Weston County  Wyoming         2022-09-01   
122264  56045_2022-10-01  56045   Weston County  Wyoming         2022-10-01   

        microbusiness_density  active  
0                    3.007682    1249  
1                    2.884870    1198  
2                    3.055843    1269  
3                    2.993233    1243  
4                    2.993233    1243  
...                       ...     ...  
122260               1.803249     101  
122261               1.803249     101  
122262               1.785395     100  
122263               1.785395     100  
122264               1.785395     100  

[122265 rows x 7 columns]

In [3]:
cf = train['cfips'].values

In [4]:
cf

array([ 1001,  1001,  1001, ..., 56045, 56045, 56045], dtype=int64)

In [5]:
cfips = np.unique(cf) # 중복제거

In [6]:
cfips

array([ 1001,  1003,  1005, ..., 56041, 56043, 56045], dtype=int64)

In [7]:
fdom = train['first_day_of_month']

In [8]:
fdom

0         2019-08-01
1         2019-09-01
2         2019-10-01
3         2019-11-01
4         2019-12-01
             ...    
122260    2022-06-01
122261    2022-07-01
122262    2022-08-01
122263    2022-09-01
122264    2022-10-01
Name: first_day_of_month, Length: 122265, dtype: object

In [9]:
fdom1 = fdom.values

In [10]:
first_day_of_month = fdom1[0:39] # 매 county마다 39개월 간의 자료 사용

In [11]:
first_day_of_month

array(['2019-08-01', '2019-09-01', '2019-10-01', '2019-11-01',
       '2019-12-01', '2020-01-01', '2020-02-01', '2020-03-01',
       '2020-04-01', '2020-05-01', '2020-06-01', '2020-07-01',
       '2020-08-01', '2020-09-01', '2020-10-01', '2020-11-01',
       '2020-12-01', '2021-01-01', '2021-02-01', '2021-03-01',
       '2021-04-01', '2021-05-01', '2021-06-01', '2021-07-01',
       '2021-08-01', '2021-09-01', '2021-10-01', '2021-11-01',
       '2021-12-01', '2022-01-01', '2022-02-01', '2022-03-01',
       '2022-04-01', '2022-05-01', '2022-06-01', '2022-07-01',
       '2022-08-01', '2022-09-01', '2022-10-01'], dtype=object)

In [12]:
density = train['microbusiness_density'].values

In [13]:
density

array([3.0076818, 2.8848701, 3.0558431, ..., 1.7853955, 1.7853955,
       1.7853955])

In [14]:
microbusiness_density = density.reshape(3135, 39)

In [15]:
df1 = pd.DataFrame(
    microbusiness_density,
    index=cfips,
    columns=first_day_of_month)

In [16]:
df = df1.T

In [17]:
df

1001      1003      1005      1007      1009      1011   \
2019-08-01  3.007682  7.239156  1.073138  1.310777  1.544148  0.926372   
2019-09-01  2.884870  7.290936  0.995794  1.305176  1.575892  0.998556   
2019-10-01  3.055843  7.425439  1.160149  1.254761  1.546415  0.974495   
2019-11-01  2.993233  7.426071  1.000628  1.254761  1.573625  1.022618   
2019-12-01  2.993233  7.470274  1.000628  1.265965  1.555485  1.034649   
2020-01-01  2.969090  7.413655  1.027229  1.253638  1.573217  1.060717   
2020-02-01  2.909326  7.282522  1.022314  1.248041  1.536999  1.036333   
2020-03-01  2.933231  7.309610  1.032144  1.264831  1.541526  1.060717   
2020-04-01  3.000167  7.568799  1.086209  1.270428  1.577744  1.011948   
2020-05-01  3.004948  7.603275  1.081294  1.287217  1.575481  0.890027   
2020-06-01  3.019292  7.708551  0.997739  1.304007  1.570953  0.926603   
2020-07-01  3.083837  7.783045  0.987909  1.343183  1.602644  0.914411   
2020-08-01  3.174679  7.853229  0.982994  1.304007  1.604907  0.950988   
2020-09-01  3.205756  8.412239  1.022314  1.320797  1.647916  0.926603   
2020-10-01  3.193804  8.329126  1.037059  1.326394  1.641125  0.938795   
2020-11-01  3.038416  8.263252  1.032144  1.320797  1.641125  0.877835   
2020-12-01  3.002558  8.224466  1.032144  1.309604  1.613962  0.877835   
2021-01-01  2.947244  8.011045  1.111998  1.310044  1.612029  0.862069   
2021-02-01  3.106106  7.909001  1.072105  1.287650  1.688793  0.800493   
2021-03-01  3.144043  7.978031  1.057146  1.287650  1.700081  0.825123   
2021-04-01  3.224659  8.032654  1.102025  1.259657  1.702339  0.862069   
2021-05-01  3.227030  8.061466  1.097038  1.259657  1.720401  0.874384   
2021-06-01  3.222288  8.077073  1.107011  1.237263  1.713628  0.874384   
2021-07-01  3.210433  7.984033  1.146903  1.237263  1.715885  0.837438   
2021-08-01  3.219917  7.918605  1.156876  1.209271  1.711370  0.825123   
2021-09-01  3.186722  7.802155  1.121971  1.186877  1.729432  0.800493   
2021-10-01  3.203320  7.832168  1.136930  1.186877  1.731690  0.775862   
2021-11-01  3.200948  7.900597  1.151890  1.231665  1.733947  0.800493   
2021-12-01  3.286307  7.930010  1.151890  1.209271  1.752009  0.837438   
2022-01-01  3.296781  7.733397  1.186629  1.214165  1.752923  0.848746   
2022-02-01  3.334431  7.823300  1.206827  1.236650  1.777708  0.874082   
2022-03-01  3.336785  7.945311  1.196728  1.264755  1.797986  0.924753   
2022-04-01  3.372082  7.979170  1.191678  1.253513  1.764189  0.912085   
2022-05-01  3.313253  7.907365  1.186629  1.247892  1.748417  0.912085   
2022-06-01  3.346197  8.507496  1.191678  1.275998  1.773202  0.937421   
2022-07-01  3.437971  8.573463  1.216926  1.326588  1.831783  0.950089   
2022-08-01  3.423852  8.491150  1.196728  1.292861  1.836289  0.962757   
2022-09-01  3.442677  8.341701  1.206827  1.315346  1.852060  0.975424   
2022-10-01  3.463856  8.359798  1.232074  1.287240  1.831783  0.988092   

               1013      1015      1017      1019   ...     56027     56029  \
2019-08-01  0.674981  2.691544  1.486542  1.104277  ...  1.150575  5.916088   
2019-09-01  0.739265  2.703752  1.355156  1.089747  ...  1.150575  5.894528   
2019-10-01  0.713551  2.693764  1.355156  1.084903  ...  1.150575  5.881592   
2019-11-01  1.054256  2.739270  1.362664  1.084903  ...  1.200600  5.954897   
2019-12-01  1.054256  2.729281  1.343894  1.089747  ...  1.200600  5.911776   
2020-01-01  1.060871  2.719628  1.319910  1.079399  ...  1.218893  5.901441   
2020-02-01  1.060871  2.745211  1.331096  1.069675  ...  1.269680  5.871155   
2020-03-01  1.009121  2.756335  1.301268  1.074537  ...  1.269680  5.897114   
2020-04-01  0.996183  2.818625  1.327368  1.059950  ...  1.269680  5.979319   
2020-05-01  0.996183  2.834197  1.342282  1.084261  ...  1.320467  6.005279   
2020-06-01  1.002652  2.853107  1.342282  1.059950  ...  1.371254  6.022585   
2020-07-01  0.763309  2.887589  1.349739  1.074537  ...  1.320467  6.009605   
2020-08-01  0.769778  2.917